services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: unless-stopped
    volumes:
      - ./env:/bot/env:ro
      - ./database:/bot/database